### ISSUE TITLE
Insecure source warning from bundle-audit

### ISSUE THREAD

**Issue by obromios** [stefanpenner/country_select#106]
The [bundler-audit](https://github.com/rubysec/bundler-audit) gem has just started to give the following warning concerning the country_select gem:
```Insecure Source URI found: git://github.com/stefanpenner/country_select.git```
I do not know why this warning has just started.

**Comment by scudco** [comment]
I think this may be an issue that should be opened on `bundler-audit` since it's not a library that `country_select` explicitly supports. Feel free to update this issue if you find out the problem, though.

**Comment by obromios** [comment]
I raised the issue with bundler-audit. The warning is because in your README.me file, you specify to download the gem using
```gem 'country_select', github: 'stefanpenner/country_select'```
However this uses the insecure http protocol and leaves the user of your gem open to Man-in-the-middle-attack. Instead, the instruction should read
```gem 'country_select', :git => 'https://github.com/stefanpenner/country_select'```
which eliminates the  Man-in-the-middle-attack risk and bundler-audit no longer gives a warning.

I note that the warning also disappears if you use
```gem 'country_select'```
in the Gemfile.  I am curious why you suggest the users download the gem from github rather than Rubygems given you appear to be keeping Rubygems up to date?

**Comment by scudco** [comment]
I think the README.md should be updated. I think we had set it to `github: 'stefanpenner/country_select'` because 2.0 was in development for a while and it was confusing people who came to github to read the README

You say it's still happening with `gem 'country_select'`? Any idea what's going on there?

FWIW, if `bundler-audit` hasn't already raised the `github:` directive using an insecure protocol with the bundler team, then that seems like the root worth striking since `github:` is a valid and widely used directive.

Thanks for explaining this to me further.

**Comment by obromios** [comment]
I might not have been clear, just putting
```gem 'country_select'```
does work, and does not raise a warning from bundle-audit.
I agree that many people could be caught out using just github:, so I will check to see if they have raised it with the bundler team.

**Comment by scudco** [comment]
oh, sorry, I completely misread your message. I honestly read it as "I note that the warning also _appears_ if you use" hah, sorry

Okay, I'll update the README now. Thanks again.
