### ISSUE TITLE
Incomplete names of country

### ISSUE THREAD

**Issue by chashmeetsingh** [stefanpenner/country_select#113]
The is is returning incomplete names of the countries
For eg: 
Bolivia, Plurinational State of
Congo, The Democratic Republic of the
Iran, Islamic Republic of
and some more

**Comment by scudco** [comment]
The English names come from the ISO-3166 designations for country names.

https://en.wikipedia.org/wiki/ISO_3166

Are you seeing some deviation from these in the list of country names?

**Comment by chashmeetsingh** [comment]
deviation as in complete names are not printed instead i am getting only a part check the above for an example

**Comment by scudco** [comment]
I assume you are referencing the ordering of the country names? Currently, they are listed such that when an English-speaking person is looking for `Congo`, they can find it under the C's rather than the T's or the D's. That is, `Congo, The Democratic Republic of the` is easier to locate than `The Democratic Republic of the Congo` or `Democratic Republic of the Congo`.

**Comment by chashmeetsingh** [comment]
oh okk thanks for the info
