### ISSUE TITLE
Add custom option to collection

### ISSUE THREAD

**Issue by tenzanoni** [stefanpenner/country_select#141]
I wanna add a custom option(has value) for country_select. Tried several but non of them works. How could i add custom option for country select? or is there a way to call country collection for me to add new option

**Comment by tkz79** [comment]
+1

**Comment by scudco** [comment]
@tkz79 thanks for adding this approach. I like it.

Does this help you @tenzanoni ?


In a future version, I think it'd be nice to be able to do this without necessarily registering a new country so as not to mess with data that other libraries may depend on. But whatever implementation might be created in the future should probably look a lot like this since `country_select` depends so much on the `countries` gem's data structure.
