### ISSUE TITLE
Duplicate countries for Zulu

### ISSUE THREAD

**Issue by adrianmann** [stefanpenner/country_select#216]
It appears that using the Zulu country code zu is returning duplicate countries. I am unsure whether this is an issue in our setup or if this is the expected list for the zu code. Can anyone confirm or point me in the right direction?

![Screenshot from 2023-01-17 23-06-29](https://user-images.githubusercontent.com/2901777/213031882-47390125-f25c-4589-bf52-cfc8c03fa305.png)

This is an example of our select box:
```
<div>
   <%= country_select "country_code", :country_code, {selected: @user.country_code, only: Rails.application.config.country_codes} %>
</div>
```

**Comment by pmor** [comment]
(Issue transferred over to `country_select` repo.)

@adrianmann From the code example, I suspect you might have duplicate country codes in `Rails.application.config.country_codes`, since the array provided to `only:` will override the list of countries.

Looking at that screenshot, you might be using an older version of `countries` and/or `country_select` gems, as some of those names don't match the latest versions of the gems, and there could be issues with the translations in older versions.
