### ISSUE TITLE
How would I add a place holder option like the example below:

### ISSUE THREAD

**Issue by MarkMurphy** [stefanpenner/country_select#90]
Firefox and Chrome seem to do this:

```html
<option value='' disabled selected style='display:none;'>Please Choose</option>
```

**Comment by scudco** [comment]
This is supported with Rails's `prompt` option on select tags:

```ruby
country_select(:country_code, prompt: 'Select your country')
```

Though, it will not produce the markup you pasted. It will produce:

```html
<option value="">Select your country</option>
```

Since country_select just proxies those options to the Rails `select` helper, I think it'd be best to open an issue on [Rails ActionView](https://github.com/rails/rails/tree/master/actionview) if you want to see that kind of markup produced by the `prompt` option.
