### ISSUE TITLE
Incorrectly detects Rails 3 as 4 when using Ransack gem

### ISSUE THREAD

**Issue by geneccx** [stefanpenner/country_select#99]
So, this is a pretty strange interaction which was causing me trouble with ActiveAdmin 1, which uses Ransack.

Ransack opens up ActionView::Helpers::Tags::Base in
ransack-1.6.3/lib/ransack/helpers/form_builder.rb:
```
# This patch is needed since this Rails commit:
# https://github.com/rails/rails/commit/c1a118a
#
# TODO: Find a better way to solve this.
#
module ActionView::Helpers::Tags
  class Base
    private
    def value(object)
      object.send @method_name if object # use send instead of public_send
    end
  end
end
```

Which breaks the condition in country_select.rb:

```
if defined?(ActionView::Helpers::Tags::Base)
```

Causing it to require the wrong country_select_helper.rb, which doesn't work in Rails 3.

I'm not sure whether to file this issue with this gem, or Ransack, but hopefully this can be resolved one way or another.

**Comment by scudco** [comment]
It looks to me like Ransack is creating a module that should not exist in Rails 3. They're stepping on an object space that should be owned by ActionView.

It's possible `country_select` could do a better job of testing deeper object support and inferring the Rails version. I had chosen to test for the module definition because that seemed more future-proof than explicitly asking for the Rails version and switching based on that.

I'm closing this, but feel free to post any workarounds you may have found here.
